# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contract_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('r', 'Resolved')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
