# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('passenger_type', models.CharField(blank=True, max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tkt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ticketing_issu_date', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('departure_date', models.DateTimeField()),
                ('interface_id', models.CharField(max_length=30)),
                ('payement_card', models.CharField(max_length=50, null=True)),
                ('ticketing_pcc', models.CharField(max_length=50, null=True)),
                ('ticketing_agent', models.CharField(max_length=50, null=True)),
                ('ticket_issu_date', models.DateTimeField(blank=True, null=True)),
                ('carriers', models.CharField(max_length=100, null=True)),
                ('validating_carrier', models.CharField(max_length=100, null=True)),
                ('class_of_service', models.CharField(max_length=50, null=True)),
                ('frequent_flyer', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_pcc', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_agent', models.CharField(blank=True, max_length=50, null=True)),
                ('is_ticketed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchedChange',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dk', models.CharField(max_length=30)),
                ('cc_agent', models.CharField(max_length=30)),
                ('t_pcc', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('pax_names', models.CharField(blank=True, default='ANY', max_length=500)),
                ('is_ticket', models.BooleanField(default=False)),
                ('booking_pcc', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_agent', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identication', models.CharField(blank=True, max_length=30, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.Passenger')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.Reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers', through='gds.Travel', to='gds.Passenger'),
        ),
    ]
