# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
