# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSetting',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=50)),
                ('database', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
